---
- name: Configure Servers and Update Software
  hosts: all
  become: true

  tasks:
    - name: Comment out Cloud Config Lines
      block:
        - name: Comment out set_hostname in cloud.cfg
          replace:
            path: /etc/cloud/cloud.cfg
            regexp: '^(\\s*- set_hostname)'
            replace: '#\\1'

        - name: Comment out update_hostname in cloud.cfg
          replace:
            path: /etc/cloud/cloud.cfg
            regexp: '^(\\s*- update_hostname)'
            replace: '#\\1'

        - name: Comment out update_etc_hosts in cloud.cfg
          replace:
            path: /etc/cloud/cloud.cfg
            regexp: '^(\\s*- update_etc_hosts)'
            replace: '#\\1'
          
        - name: Update cloud.cfg for preserving hostname
          lineinfile:
            path: /etc/cloud/cloud.cfg
            regexp: '^preserve_hostname:'
            line: 'preserve_hostname: true'
            state: present
      when: inventory_hostname != ansible_hostname

    - name: Update and Upgrade Ubuntu VMs
      block:
        - name: Update package cache
          apt:
            update_cache: yes

        - name: Upgrade packages
          apt:
            upgrade: dist

        - name: Autoremove unused packages
          apt:
            autoremove: yes

    - name: Update Hostname and Hosts File
      block:
        - name: Set hostname
          hostname:
            name: "{{ inventory_hostname }}"

        - name: Update /etc/hostname
          lineinfile:
            path: /etc/hostname
            line: "{{ inventory_hostname }}"
          when: inventory_hostname != ansible_hostname

        - name: Update /etc/hosts
          lineinfile:
            path: /etc/hosts
            regexp: '^127.0.1.1\\s+.*$'
            line: '127.0.1.1 {{ inventory_hostname }}'
      when: inventory_hostname in groups['testing']
