- name: Update and Upgrade Ubuntu VMs
  hosts: all
  become: true
  tasks:
  - name: Update package cache
    apt:
      update_cache: yes

  - name: Upgrade packages
    apt:
      upgrade: dist

  - name: Autoremove unused packages
    apt:
      autoremove: yes
