- name: Run kubeadm init command
  hosts: k8s-cntlr[0]
  become: true
  remote_user: ubuntu
  vars:
    join_command_location: "join_command.out"
    home_dir: "/home/ubuntu"

  tasks:
  - name: Display kubeadm init output
    debug:
      var: kubeadm_output.stdout_lines

  - name: restart containerd
    service:
      name: containerd
      state: restarted

  - name: Initialize Kubernetes cluster
    command: "sudo kubeadm init --pod-network-cidr=10.165.0.0/16  --control-plane-endpoint=192.168.10.5"
    args:
      creates: /etc/kubernetes/admin.conf # skip this task if the file already exists
    register: kube_init

  - name: show kube init info
    debug:
      var: kube_init

  - name: Create .kube directory in user home
    file:
      path: "{{ home_dir }}/.kube"
      state: directory
      owner: 1000
      group: 1000
  - name: Configure .kube/config files in user home
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "{{ home_dir }}/.kube/config"
      remote_src: yes
      owner: 1000
      group: 1000

  - name: restart kubelet for config changes
    service:
      name: kubelet
      state: restarted

  - name: get flannel networking
    get_url:
      url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      dest: "{{ home_dir }}/kube-flannel.yml"

  - name: apply flannel networking
    become: no
    command: kubectl apply -f "{{ home_dir }}/kube-flannel.yml"

  - name: get dashboard
    get_url:
      url: https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
      dest: "{{ home_dir }}/dashboard.yaml"

  - name: apply dashboard
    become: no
    command: kubectl apply -f "{{ home_dir }}/dashboard.yaml"
