---
- name: Configure Ceph Installation
  hosts: loadbalancer
  become: true
  tasks:
    - name: Download cephadm script
      shell: curl --silent --remote-name --location https://download.ceph.com/rpm-18.2.0/el9/noarch/cephadm

    - name: Make cephadm script executable
      file:
        path: cephadm
        mode: '0755'

    - name: Add Ceph repository
      command: ./cephadm add-repo --release reef
      args:
        chdir: "{{ ansible_user_dir }}"

    - name: Install Ceph using cephadm
      command: ./cephadm install
      args:
        chdir: "{{ ansible_user_dir }}"

    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "192.168.10.5 kube-andreas-01.local.lan"
        - "192.168.10.6 ceph-01.local.lan"
        - "192.168.10.7 ceph-02.local.lan"
        - "192.168.10.8 ceph-03.local.lan"
