---
- name: Deploy and Configure Prometheus Operator
  hosts: k8s-cntlr[0]
  vars:
    home_dir: "/home/tshepo"


  tasks:
    - name: Clone kube-prometheus repository
      git:
        repo: https://github.com/prometheus-operator/kube-prometheus.git
        dest: "{{ home_dir }}/kube-prometheus"
      register: git_clone_result

    - name: Create Prometheus setup resources
      command: kubectl create -f "{{ home_dir }}/kube-prometheus/manifests/setup"
      when: git_clone_result is success

    - name: Wait for pods to be running
      command: kubectl wait --for=condition=Ready pod --all -n monitoring
      changed_when: false

    - name: Delete network policies
      command: kubectl -n monitoring delete networkpolicies.networking.k8s.io --all

    - name: Create shell script for service patching
      copy:
        content: |
          #!/bin/bash
          kubectl --namespace monitoring patch svc prometheus-k8s -p '{"spec": {"type": "LoadBalancer"}}'
          kubectl --namespace monitoring patch svc alertmanager-main -p '{"spec": {"type": "LoadBalancer"}}'
          kubectl --namespace monitoring patch svc grafana -p '{"spec": {"type": "LoadBalancer"}}'
          kubectl --namespace kubernetes-dashboard patch svc kubernetes-dashboard -p '{"spec": {"type": "LoadBalancer"}}'
        dest: "{{ home_dir }}/patch-services.sh"
        mode: '0755'

- name: Run the shell script
  hosts: k8s-cntlr[0]
  tasks:
    - name: Run patch-services.sh
      command: "{{ home_dir }}/patch-services.sh"
      args:
        chdir: "{{ home_dir }}"